# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      "${fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }}/lenovo/thinkpad/x230"
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c6270c79-5888-4a79-b603-cf8405434351";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6CEA-2D87";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ace19c42-6dcf-45d0-bfa8-17177e6422cd"; }
    ];

  boot.resumeDevice = "/dev/disk/by-uuid/ace19c42-6dcf-45d0-bfa8-17177e6422cd";
  boot.kernelParams = [
    "resume=UUID=ace19c42-6dcf-45d0-bfa8-17177e6422cd"
  ];

  boot.loader = {
    systemd-boot.enable = lib.mkForce false;
    grub = {
      enable = true;
      device = "/dev/sda";
    };
  };

  services.tlp = {
    enable = true;
    # https://wiki.archlinux.org/title/Lenovo_ThinkPad_X230#TLP
    settings = {
      START_CHARGE_THRESH_BAT0 = 67;
      STOP_CHARGE_THRESH_BAT0  = 100;
    };
  };

  services.xremap = {
    deviceNames = [
      "AT Translated Set 2 keyboard"
      "ThinkPad Extra Buttons"
      "Video Bus"
    ];
    config.keymap = [
      {
        name = "Thinkpad specific";
        "Win-Ctrl-Shift-M".launch = "${pkgs.alsa-utils}/bin/amixer sset 'Master',0 toggle";
        "KEY_MUTE".launch = "${pkgs.alsa-utils}/bin/amixer sset 'Master',0 toggle";
      }
    ];
  };

  config = lib.mkIf config.sway.enable {
    wayland.windowManager.sway.config.startup = [
      { command = "systemctl --user restart xremap"; always = true; }
    ];
  };


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
