# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ./lan.nix
    ];

  has_nvidia_gpu = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e05411b2-65ec-4afa-8ca4-f137c40acc0f";
      fsType = "btrfs";
    };

  # sudo parted /dev/sdX -- mklabel gpt
  # sudo parted /dev/sdX -- mkpart primary btrfs 1MiB 100%
  # sudo mkfs.btrfs -L media /dev/sdX1
  # sudo mkdir -p /mnt/media
  # sudo mount UUID=<UUID> /mnt/media
  # sudo btrfs subvolume create /mnt/media/media
  # sudo mkdir -p /mnt/media/media/{Music,Videos,Pictures}
  # sudo umount /mnt/media
  # sudo rmdir /mnt/media
  fileSystems."/srv/media" = {
    device = "/dev/disk/by-uuid/88521b04-538b-41a4-8ad1-c6c750713e3b";
    fsType = "btrfs";
    options = [
      "subvol=media"
    ];
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6B27-AB52";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # sudo btrfs filesystem mkswapfile --size 32G /swapfile
  swapDevices = [{
    device = "/swapfile";
    size = 32*1024; # 32 GiB
  }];

  boot.resumeDevice = "/dev/disk/by-uuid/e05411b2-65ec-4afa-8ca4-f137c40acc0f";
  boot.kernelParams = [
    # findmnt -no UUID /
    "resume=UUID=e05411b2-65ec-4afa-8ca4-f137c40acc0f"
    # sudo btrfs inspect-internal map-swapfile -r /swapfile
    "13777487"
    "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
  ];

  hardware.nvidia.powerManagement.enable = true;


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0f3u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
